name: sales-forecasting-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - pip
  - pip:
    - mlflow>=2.0.0
    - pandas>=1.5.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - matplotlib>=3.6.0
    - seaborn>=0.12.0
    - xgboost>=1.7.0
    - joblib>=1.3.0
    - requests>=2.28.0
    - pytest>=7.0.0
    - pytest-timeout>=2.1.0
